export const MediaGenres = [
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Ecchi',
  'Fantasy',
  'Hentai',
  'Horror',
  'Mahou Shoujo',
  'Mecha',
  'Music',
  'Mystery',
  'Psychological',
  'Romance',
  'Sci-Fi',
  'Slice of Life',
  'Sports',
  'Supernatural',
  'Thriller',
];

export const MediaTags = [
  '4-koma',
  'Achromatic',
  'Achronological Order',
  'Acrobatics',
  'Acting',
  'Adoption',
  'Advertisement',
  'Afterlife',
  'Age Gap',
  'Age Regression',
  'Agender',
  'Agriculture',
  'Ahegao',
  'Airsoft',
  'Alchemy',
  'Aliens',
  'Alternate Universe',
  'American Football',
  'Amnesia',
  'Amputation',
  'Anachronism',
  'Anal Sex',
  'Ancient China',
  'Angels',
  'Animals',
  'Anthology',
  'Anthropomorphism',
  'Anti-Hero',
  'Archery',
  'Armpits',
  'Aromantic',
  'Arranged Marriage',
  'Artificial Intelligence',
  'Asexual',
  'Ashikoki',
  'Asphyxiation',
  'Assassins',
  'Astronomy',
  'Athletics',
  'Augmented Reality',
  'Autobiographical',
  'Aviation',
  'Badminton',
  'Band',
  'Bar',
  'Baseball',
  'Basketball',
  'Battle Royale',
  'Biographical',
  'Bisexual',
  'Blackmail',
  'Board Game',
  'Boarding School',
  'Body Horror',
  'Body Swapping',
  'Bondage',
  'Boobjob',
  'Bowling',
  'Boxing',
  "Boys' Love",
  'Bullying',
  'Butler',
  'Calligraphy',
  'Cannibalism',
  'Card Battle',
  'Cars',
  'Centaur',
  'Cervix Penetration',
  'CGI',
  'Cheerleading',
  'Chibi',
  'Chimera',
  'Chuunibyou',
  'Circus',
  'Class Struggle',
  'Classic Literature',
  'Classical Music',
  'Clone',
  'Coastal',
  'College',
  'Coming of Age',
  'Conspiracy',
  'Cosmic Horror',
  'Cosplay',
  'Cowboys',
  'Crime',
  'Criminal Organization',
  'Crossdressing',
  'Crossover',
  'Cult',
  'Cultivation',
  'Cumflation',
  'Cunnilingus',
  'Cute Boys Doing Cute Things',
  'Cute Girls Doing Cute Things',
  'Cyberpunk',
  'Cyborg',
  'Cycling',
  'Dancing',
  'Death Game',
  'Deepthroat',
  'Defloration',
  'Delinquents',
  'Demons',
  'Denpa',
  'Desert',
  'Detective',
  'DILF',
  'Dinosaurs',
  'Disability',
  'Dissociative Identities',
  'Double Penetration',
  'Dragons',
  'Drawing',
  'Drugs',
  'Dullahan',
  'Dungeon',
  'Dystopian',
  'E-Sports',
  'Eco-Horror',
  'Economics',
  'Educational',
  'Elderly Protagonist',
  'Elf',
  'Ensemble Cast',
  'Environmental',
  'Episodic',
  'Ero Guro',
  'Espionage',
  'Estranged Family',
  'Exhibitionism',
  'Facial',
  'Fairy',
  'Fairy Tale',
  'Fake Relationship',
  'Family Life',
  'Fashion',
  'Feet',
  'Fellatio',
  'Female Harem',
  'Female Protagonist',
  'Femboy',
  'Femdom',
  'Fencing',
  'Filmmaking',
  'Firefighters',
  'Fishing',
  'Fisting',
  'Fitness',
  'Flash',
  'Flat Chest',
  'Food',
  'Football',
  'Foreign',
  'Found Family',
  'Fugitive',
  'Full CGI',
  'Full Color',
  'Futanari',
  'Gambling',
  'Gangs',
  'Gender Bending',
  'Ghost',
  'Go',
  'Goblin',
  'Gods',
  'Golf',
  'Gore',
  'Group Sex',
  'Guns',
  'Gyaru',
  'Hair Pulling',
  'Handball',
  'Handjob',
  'Henshin',
  'Heterosexual',
  'Hikikomori',
  'Hip-hop Music',
  'Historical',
  'Homeless',
  'Horticulture',
  'Human Pet',
  'Hypersexuality',
  'Ice Skating',
  'Idol',
  'Incest',
  'Inn',
  'Inseki',
  'Irrumatio',
  'Isekai',
  'Iyashikei',
  'Jazz Music',
  'Josei',
  'Judo',
  'Kaiju',
  'Karuta',
  'Kemonomimi',
  'Kids',
  'Kingdom Management',
  'Konbini',
  'Kuudere',
  'Lacrosse',
  'Lactation',
  'Language Barrier',
  'Large Breasts',
  'LGBTQ+ Themes',
  'Lost Civilization',
  'Love Triangle',
  'Mafia',
  'Magic',
  'Mahjong',
  'Maids',
  'Makeup',
  'Male Harem',
  'Male Pregnancy',
  'Male Protagonist',
  'Marriage',
  'Martial Arts',
  'Masochism',
  'Masturbation',
  'Matchmaking',
  'Mating Press',
  'Matriarchy',
  'Medicine',
  'Memory Manipulation',
  'Mermaid',
  'Meta',
  'Metal Music',
  'MILF',
  'Military',
  'Mixed Gender Harem',
  'Monster Boy',
  'Monster Girl',
  'Mopeds',
  'Motorcycles',
  'Mountaineering',
  'Musical Theater',
  'Mythology',
  'Nakadashi',
  'Natural Disaster',
  'Necromancy',
  'Nekomimi',
  'Netorare',
  'Netorase',
  'Netori',
  'Ninja',
  'No Dialogue',
  'Noir',
  'Non-fiction',
  'Nudity',
  'Nun',
  'Office',
  'Office Lady',
  'Oiran',
  'Ojou-sama',
  'Omegaverse',
  'Orphan',
  'Otaku Culture',
  'Outdoor',
  'Pandemic',
  'Parenthood',
  'Parkour',
  'Parody',
  'Pet Play',
  'Philosophy',
  'Photography',
  'Pirates',
  'Poker',
  'Police',
  'Politics',
  'Polyamorous',
  'Post-Apocalyptic',
  'POV',
  'Pregnant',
  'Primarily Adult Cast',
  'Primarily Animal Cast',
  'Primarily Child Cast',
  'Primarily Female Cast',
  'Primarily Male Cast',
  'Primarily Teen Cast',
  'Prison',
  'Prostitution',
  'Proxy Battle',
  'Psychosexual',
  'Public Sex',
  'Puppetry',
  'Rakugo',
  'Rape',
  'Real Robot',
  'Rehabilitation',
  'Reincarnation',
  'Religion',
  'Restaurant',
  'Revenge',
  'Rimjob',
  'Robots',
  'Rock Music',
  'Rotoscoping',
  'Royal Affairs',
  'Rugby',
  'Rural',
  'Sadism',
  'Samurai',
  'Satire',
  'Scat',
  'School',
  'School Club',
  'Scissoring',
  'Scuba Diving',
  'Seinen',
  'Sex Toys',
  'Shapeshifting',
  'Ships',
  'Shogi',
  'Shoujo',
  'Shounen',
  'Shrine Maiden',
  'Skateboarding',
  'Skeleton',
  'Slapstick',
  'Slavery',
  'Snowscape',
  'Software Development',
  'Space',
  'Space Opera',
  'Spearplay',
  'Squirting',
  'Steampunk',
  'Stop Motion',
  'Succubus',
  'Suicide',
  'Sumata',
  'Sumo',
  'Super Power',
  'Super Robot',
  'Superhero',
  'Surfing',
  'Surreal Comedy',
  'Survival',
  'Sweat',
  'Swimming',
  'Swordplay',
  'Table Tennis',
  'Tanks',
  'Tanned Skin',
  'Teacher',
  "Teens' Love",
  'Tennis',
  'Tentacles',
  'Terrorism',
  'Threesome',
  'Time Loop',
  'Time Manipulation',
  'Time Skip',
  'Tokusatsu',
  'Tomboy',
  'Torture',
  'Tragedy',
  'Trains',
  'Transgender',
  'Travel',
  'Triads',
  'Tsundere',
  'Twins',
  'Unrequited Love',
  'Urban',
  'Urban Fantasy',
  'Vampire',
  'Veterinarian',
  'Video Games',
  'Vikings',
  'Villainess',
  'Virginity',
  'Virtual World',
  'Volleyball',
  'Vore',
  'Voyeur',
  'VTuber',
  'War',
  'Watersports',
  'Werewolf',
  'Witch',
  'Work',
  'Wrestling',
  'Writing',
  'Wuxia',
  'Yakuza',
  'Yandere',
  'Youkai',
  'Yuri',
  'Zombie',
  'Zoophilia',
];
